// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializecancelProcessRequest")
public inline fun cancelProcessRequest(block: CancelProcessRequestKt.Dsl.() -> kotlin.Unit): Messages.CancelProcessRequest =
  CancelProcessRequestKt.Dsl._create(Messages.CancelProcessRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `CancelProcessRequest`
 */
public object CancelProcessRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Messages.CancelProcessRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Messages.CancelProcessRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Messages.CancelProcessRequest = _builder.build()

    /**
     * `string origin = 1;`
     */
    public var origin: kotlin.String
      @JvmName("getOrigin")
      get() = _builder.getOrigin()
      @JvmName("setOrigin")
      set(value) {
        _builder.setOrigin(value)
      }
    /**
     * `string origin = 1;`
     */
    public fun clearOrigin() {
      _builder.clearOrigin()
    }

    /**
     * `.AuthData authData = 2;`
     */
    public var authData: Messages.AuthData
      @JvmName("getAuthData")
      get() = _builder.getAuthData()
      @JvmName("setAuthData")
      set(value) {
        _builder.setAuthData(value)
      }
    /**
     * `.AuthData authData = 2;`
     */
    public fun clearAuthData() {
      _builder.clearAuthData()
    }
    /**
     * `.AuthData authData = 2;`
     * @return Whether the authData field is set.
     */
    public fun hasAuthData(): kotlin.Boolean {
      return _builder.hasAuthData()
    }
    public val CancelProcessRequestKt.Dsl.authDataOrNull: Messages.AuthData?
      get() = _builder.authDataOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Messages.CancelProcessRequest.copy(block: CancelProcessRequestKt.Dsl.() -> kotlin.Unit): Messages.CancelProcessRequest =
  CancelProcessRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val Messages.CancelProcessRequestOrBuilder.authDataOrNull: Messages.AuthData?
  get() = if (hasAuthData()) getAuthData() else null

