// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializecancelProcessResponse")
public inline fun cancelProcessResponse(block: CancelProcessResponseKt.Dsl.() -> kotlin.Unit): Messages.CancelProcessResponse =
  CancelProcessResponseKt.Dsl._create(Messages.CancelProcessResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `CancelProcessResponse`
 */
public object CancelProcessResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Messages.CancelProcessResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Messages.CancelProcessResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Messages.CancelProcessResponse = _builder.build()

    /**
     * `bool successes = 1;`
     */
    public var successes: kotlin.Boolean
      @JvmName("getSuccesses")
      get() = _builder.getSuccesses()
      @JvmName("setSuccesses")
      set(value) {
        _builder.setSuccesses(value)
      }
    /**
     * `bool successes = 1;`
     */
    public fun clearSuccesses() {
      _builder.clearSuccesses()
    }

    /**
     * `optional .MetaError error = 2;`
     */
    public var error: Messages.MetaError
      @JvmName("getError")
      get() = _builder.getError()
      @JvmName("setError")
      set(value) {
        _builder.setError(value)
      }
    /**
     * `optional .MetaError error = 2;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `optional .MetaError error = 2;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }
    public val CancelProcessResponseKt.Dsl.errorOrNull: Messages.MetaError?
      get() = _builder.errorOrNull

    /**
     * `.AuthData authData = 3;`
     */
    public var authData: Messages.AuthData
      @JvmName("getAuthData")
      get() = _builder.getAuthData()
      @JvmName("setAuthData")
      set(value) {
        _builder.setAuthData(value)
      }
    /**
     * `.AuthData authData = 3;`
     */
    public fun clearAuthData() {
      _builder.clearAuthData()
    }
    /**
     * `.AuthData authData = 3;`
     * @return Whether the authData field is set.
     */
    public fun hasAuthData(): kotlin.Boolean {
      return _builder.hasAuthData()
    }
    public val CancelProcessResponseKt.Dsl.authDataOrNull: Messages.AuthData?
      get() = _builder.authDataOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Messages.CancelProcessResponse.copy(block: CancelProcessResponseKt.Dsl.() -> kotlin.Unit): Messages.CancelProcessResponse =
  CancelProcessResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val Messages.CancelProcessResponseOrBuilder.errorOrNull: Messages.MetaError?
  get() = if (hasError()) getError() else null

public val Messages.CancelProcessResponseOrBuilder.authDataOrNull: Messages.AuthData?
  get() = if (hasAuthData()) getAuthData() else null

