// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializeregisterClientResponse")
public inline fun registerClientResponse(block: RegisterClientResponseKt.Dsl.() -> kotlin.Unit): Messages.RegisterClientResponse =
  RegisterClientResponseKt.Dsl._create(Messages.RegisterClientResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `RegisterClientResponse`
 */
public object RegisterClientResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Messages.RegisterClientResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Messages.RegisterClientResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Messages.RegisterClientResponse = _builder.build()

    /**
     * `string macLabel = 1;`
     */
    public var macLabel: kotlin.String
      @JvmName("getMacLabel")
      get() = _builder.getMacLabel()
      @JvmName("setMacLabel")
      set(value) {
        _builder.setMacLabel(value)
      }
    /**
     * `string macLabel = 1;`
     */
    public fun clearMacLabel() {
      _builder.clearMacLabel()
    }

    /**
     * `bytes macKey = 2;`
     */
    public var macKey: com.google.protobuf.ByteString
      @JvmName("getMacKey")
      get() = _builder.getMacKey()
      @JvmName("setMacKey")
      set(value) {
        _builder.setMacKey(value)
      }
    /**
     * `bytes macKey = 2;`
     */
    public fun clearMacKey() {
      _builder.clearMacKey()
    }

    /**
     * `optional .MetaError error = 3;`
     */
    public var error: Messages.MetaError
      @JvmName("getError")
      get() = _builder.getError()
      @JvmName("setError")
      set(value) {
        _builder.setError(value)
      }
    /**
     * `optional .MetaError error = 3;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `optional .MetaError error = 3;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }
    public val RegisterClientResponseKt.Dsl.errorOrNull: Messages.MetaError?
      get() = _builder.errorOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Messages.RegisterClientResponse.copy(block: RegisterClientResponseKt.Dsl.() -> kotlin.Unit): Messages.RegisterClientResponse =
  RegisterClientResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val Messages.RegisterClientResponseOrBuilder.errorOrNull: Messages.MetaError?
  get() = if (hasError()) getError() else null

