// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

import com.example.client_content.transaction_service.data.proto.trsanction_proto.Transactions

@kotlin.jvm.JvmName("-initializeregisterTransactionRequest")
public inline fun registerTransactionRequest(block: RegisterTransactionRequestKt.Dsl.() -> kotlin.Unit): Messages.RegisterTransactionRequest =
  RegisterTransactionRequestKt.Dsl._create(Messages.RegisterTransactionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `RegisterTransactionRequest`
 */
public object RegisterTransactionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Messages.RegisterTransactionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Messages.RegisterTransactionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Messages.RegisterTransactionRequest = _builder.build()

    /**
     * `.Transaction transaction = 1;`
     */
    public var transaction: Transactions.Transaction
      @JvmName("getTransaction")
      get() = _builder.getTransaction()
      @JvmName("setTransaction")
      set(value) {
        _builder.setTransaction(value)
      }
    /**
     * `.Transaction transaction = 1;`
     */
    public fun clearTransaction() {
      _builder.clearTransaction()
    }
    /**
     * `.Transaction transaction = 1;`
     * @return Whether the transaction field is set.
     */
    public fun hasTransaction(): kotlin.Boolean {
      return _builder.hasTransaction()
    }
    public val RegisterTransactionRequestKt.Dsl.transactionOrNull: Transactions.Transaction?
      get() = _builder.transactionOrNull

    /**
     * `string origin = 2;`
     */
    public var origin: kotlin.String
      @JvmName("getOrigin")
      get() = _builder.getOrigin()
      @JvmName("setOrigin")
      set(value) {
        _builder.setOrigin(value)
      }
    /**
     * `string origin = 2;`
     */
    public fun clearOrigin() {
      _builder.clearOrigin()
    }

    /**
     * `.AuthData authData = 3;`
     */
    public var authData: Messages.AuthData
      @JvmName("getAuthData")
      get() = _builder.getAuthData()
      @JvmName("setAuthData")
      set(value) {
        _builder.setAuthData(value)
      }
    /**
     * `.AuthData authData = 3;`
     */
    public fun clearAuthData() {
      _builder.clearAuthData()
    }
    /**
     * `.AuthData authData = 3;`
     * @return Whether the authData field is set.
     */
    public fun hasAuthData(): kotlin.Boolean {
      return _builder.hasAuthData()
    }
    public val RegisterTransactionRequestKt.Dsl.authDataOrNull: Messages.AuthData?
      get() = _builder.authDataOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Messages.RegisterTransactionRequest.copy(block: RegisterTransactionRequestKt.Dsl.() -> kotlin.Unit): Messages.RegisterTransactionRequest =
  RegisterTransactionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val Messages.RegisterTransactionRequestOrBuilder.transactionOrNull: Transactions.Transaction?
  get() = if (hasTransaction()) getTransaction() else null

public val Messages.RegisterTransactionRequestOrBuilder.authDataOrNull: Messages.AuthData?
  get() = if (hasAuthData()) getAuthData() else null

