// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messages.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
@kotlin.jvm.JvmName("-initializestartTransactionRequest")
public inline fun startTransactionRequest(block: StartTransactionRequestKt.Dsl.() -> kotlin.Unit): Messages.StartTransactionRequest =
  StartTransactionRequestKt.Dsl._create(Messages.StartTransactionRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `StartTransactionRequest`
 */
public object StartTransactionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: Messages.StartTransactionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: Messages.StartTransactionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): Messages.StartTransactionRequest = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string origin = 2;`
     */
    public var origin: kotlin.String
      @JvmName("getOrigin")
      get() = _builder.getOrigin()
      @JvmName("setOrigin")
      set(value) {
        _builder.setOrigin(value)
      }
    /**
     * `string origin = 2;`
     */
    public fun clearOrigin() {
      _builder.clearOrigin()
    }

    /**
     * `.AuthData authData = 3;`
     */
    public var authData: Messages.AuthData
      @JvmName("getAuthData")
      get() = _builder.getAuthData()
      @JvmName("setAuthData")
      set(value) {
        _builder.setAuthData(value)
      }
    /**
     * `.AuthData authData = 3;`
     */
    public fun clearAuthData() {
      _builder.clearAuthData()
    }
    /**
     * `.AuthData authData = 3;`
     * @return Whether the authData field is set.
     */
    public fun hasAuthData(): kotlin.Boolean {
      return _builder.hasAuthData()
    }
    public val StartTransactionRequestKt.Dsl.authDataOrNull: Messages.AuthData?
      get() = _builder.authDataOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun Messages.StartTransactionRequest.copy(block: StartTransactionRequestKt.Dsl.() -> kotlin.Unit): Messages.StartTransactionRequest =
  StartTransactionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val Messages.StartTransactionRequestOrBuilder.authDataOrNull: Messages.AuthData?
  get() = if (hasAuthData()) getAuthData() else null

