package com.example.client_content.transaction_service.data.proto.trsanction_proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transactions.proto
// Protobuf Java Version: 4.26.1

public final class Transactions {
  private Transactions() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Transactions.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code TransactionType}
   */
  public enum TransactionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Sale = 0;</code>
     */
    Sale(0),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TransactionType.class.getName());
    }
    /**
     * <code>Sale = 0;</code>
     */
    public static final int Sale_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransactionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TransactionType forNumber(int value) {
      switch (value) {
        case 0: return Sale;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransactionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransactionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransactionType>() {
            public TransactionType findValueByNumber(int number) {
              return TransactionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Transactions.getDescriptor().getEnumTypes().get(0);
    }

    private static final TransactionType[] VALUES = values();

    public static TransactionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransactionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TransactionType)
  }

  /**
   * Protobuf enum {@code TransactionStatus}
   */
  public enum TransactionStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Pending = 0;</code>
     */
    Pending(0),
    /**
     * <code>Failed = 1;</code>
     */
    Failed(1),
    /**
     * <code>Cancelled = 2;</code>
     */
    Cancelled(2),
    /**
     * <code>Denied = 3;</code>
     */
    Denied(3),
    /**
     * <code>Approved = 4;</code>
     */
    Approved(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TransactionStatus.class.getName());
    }
    /**
     * <code>Pending = 0;</code>
     */
    public static final int Pending_VALUE = 0;
    /**
     * <code>Failed = 1;</code>
     */
    public static final int Failed_VALUE = 1;
    /**
     * <code>Cancelled = 2;</code>
     */
    public static final int Cancelled_VALUE = 2;
    /**
     * <code>Denied = 3;</code>
     */
    public static final int Denied_VALUE = 3;
    /**
     * <code>Approved = 4;</code>
     */
    public static final int Approved_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransactionStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TransactionStatus forNumber(int value) {
      switch (value) {
        case 0: return Pending;
        case 1: return Failed;
        case 2: return Cancelled;
        case 3: return Denied;
        case 4: return Approved;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransactionStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransactionStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransactionStatus>() {
            public TransactionStatus findValueByNumber(int number) {
              return TransactionStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Transactions.getDescriptor().getEnumTypes().get(1);
    }

    private static final TransactionStatus[] VALUES = values();

    public static TransactionStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransactionStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TransactionStatus)
  }

  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TransactionStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.TransactionStatus status = 1;</code>
     * @return The status.
     */
    Transactions.TransactionStatus getStatus();

    /**
     * <code>.TransactionType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.TransactionType type = 2;</code>
     * @return The type.
     */
    Transactions.TransactionType getType();

    /**
     * <code>int32 amount = 3;</code>
     * @return The amount.
     */
    int getAmount();

    /**
     * <code>optional string referenceNumber = 4;</code>
     * @return Whether the referenceNumber field is set.
     */
    boolean hasReferenceNumber();
    /**
     * <code>optional string referenceNumber = 4;</code>
     * @return The referenceNumber.
     */
    java.lang.String getReferenceNumber();
    /**
     * <code>optional string referenceNumber = 4;</code>
     * @return The bytes for referenceNumber.
     */
    com.google.protobuf.ByteString
        getReferenceNumberBytes();

    /**
     * <code>optional string arqc = 5;</code>
     * @return Whether the arqc field is set.
     */
    boolean hasArqc();
    /**
     * <code>optional string arqc = 5;</code>
     * @return The arqc.
     */
    java.lang.String getArqc();
    /**
     * <code>optional string arqc = 5;</code>
     * @return The bytes for arqc.
     */
    com.google.protobuf.ByteString
        getArqcBytes();

    /**
     * <code>optional string maskPan = 6;</code>
     * @return Whether the maskPan field is set.
     */
    boolean hasMaskPan();
    /**
     * <code>optional string maskPan = 6;</code>
     * @return The maskPan.
     */
    java.lang.String getMaskPan();
    /**
     * <code>optional string maskPan = 6;</code>
     * @return The bytes for maskPan.
     */
    com.google.protobuf.ByteString
        getMaskPanBytes();

    /**
     * <code>optional string authorizationNumber = 7;</code>
     * @return Whether the authorizationNumber field is set.
     */
    boolean hasAuthorizationNumber();
    /**
     * <code>optional string authorizationNumber = 7;</code>
     * @return The authorizationNumber.
     */
    java.lang.String getAuthorizationNumber();
    /**
     * <code>optional string authorizationNumber = 7;</code>
     * @return The bytes for authorizationNumber.
     */
    com.google.protobuf.ByteString
        getAuthorizationNumberBytes();

    /**
     * <code>optional string stan = 8;</code>
     * @return Whether the stan field is set.
     */
    boolean hasStan();
    /**
     * <code>optional string stan = 8;</code>
     * @return The stan.
     */
    java.lang.String getStan();
    /**
     * <code>optional string stan = 8;</code>
     * @return The bytes for stan.
     */
    com.google.protobuf.ByteString
        getStanBytes();

    /**
     * <code>optional string resultCode = 9;</code>
     * @return Whether the resultCode field is set.
     */
    boolean hasResultCode();
    /**
     * <code>optional string resultCode = 9;</code>
     * @return The resultCode.
     */
    java.lang.String getResultCode();
    /**
     * <code>optional string resultCode = 9;</code>
     * @return The bytes for resultCode.
     */
    com.google.protobuf.ByteString
        getResultCodeBytes();
  }
  /**
   * Protobuf type {@code Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        Transaction.class.getName());
    }
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      status_ = 0;
      type_ = 0;
      referenceNumber_ = "";
      arqc_ = "";
      maskPan_ = "";
      authorizationNumber_ = "";
      stan_ = "";
      resultCode_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Transactions.internal_static_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Transactions.internal_static_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transactions.Transaction.class, Transactions.Transaction.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>.TransactionStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.TransactionStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public Transactions.TransactionStatus getStatus() {
      Transactions.TransactionStatus result = Transactions.TransactionStatus.forNumber(status_);
      return result == null ? Transactions.TransactionStatus.UNRECOGNIZED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <code>.TransactionType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.TransactionType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public Transactions.TransactionType getType() {
      Transactions.TransactionType result = Transactions.TransactionType.forNumber(type_);
      return result == null ? Transactions.TransactionType.UNRECOGNIZED : result;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private int amount_ = 0;
    /**
     * <code>int32 amount = 3;</code>
     * @return The amount.
     */
    @java.lang.Override
    public int getAmount() {
      return amount_;
    }

    public static final int REFERENCENUMBER_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object referenceNumber_ = "";
    /**
     * <code>optional string referenceNumber = 4;</code>
     * @return Whether the referenceNumber field is set.
     */
    @java.lang.Override
    public boolean hasReferenceNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string referenceNumber = 4;</code>
     * @return The referenceNumber.
     */
    @java.lang.Override
    public java.lang.String getReferenceNumber() {
      java.lang.Object ref = referenceNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceNumber_ = s;
        return s;
      }
    }
    /**
     * <code>optional string referenceNumber = 4;</code>
     * @return The bytes for referenceNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReferenceNumberBytes() {
      java.lang.Object ref = referenceNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARQC_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object arqc_ = "";
    /**
     * <code>optional string arqc = 5;</code>
     * @return Whether the arqc field is set.
     */
    @java.lang.Override
    public boolean hasArqc() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string arqc = 5;</code>
     * @return The arqc.
     */
    @java.lang.Override
    public java.lang.String getArqc() {
      java.lang.Object ref = arqc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arqc_ = s;
        return s;
      }
    }
    /**
     * <code>optional string arqc = 5;</code>
     * @return The bytes for arqc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArqcBytes() {
      java.lang.Object ref = arqc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arqc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MASKPAN_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object maskPan_ = "";
    /**
     * <code>optional string maskPan = 6;</code>
     * @return Whether the maskPan field is set.
     */
    @java.lang.Override
    public boolean hasMaskPan() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string maskPan = 6;</code>
     * @return The maskPan.
     */
    @java.lang.Override
    public java.lang.String getMaskPan() {
      java.lang.Object ref = maskPan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        maskPan_ = s;
        return s;
      }
    }
    /**
     * <code>optional string maskPan = 6;</code>
     * @return The bytes for maskPan.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMaskPanBytes() {
      java.lang.Object ref = maskPan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maskPan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORIZATIONNUMBER_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object authorizationNumber_ = "";
    /**
     * <code>optional string authorizationNumber = 7;</code>
     * @return Whether the authorizationNumber field is set.
     */
    @java.lang.Override
    public boolean hasAuthorizationNumber() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string authorizationNumber = 7;</code>
     * @return The authorizationNumber.
     */
    @java.lang.Override
    public java.lang.String getAuthorizationNumber() {
      java.lang.Object ref = authorizationNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorizationNumber_ = s;
        return s;
      }
    }
    /**
     * <code>optional string authorizationNumber = 7;</code>
     * @return The bytes for authorizationNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorizationNumberBytes() {
      java.lang.Object ref = authorizationNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorizationNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STAN_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stan_ = "";
    /**
     * <code>optional string stan = 8;</code>
     * @return Whether the stan field is set.
     */
    @java.lang.Override
    public boolean hasStan() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string stan = 8;</code>
     * @return The stan.
     */
    @java.lang.Override
    public java.lang.String getStan() {
      java.lang.Object ref = stan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stan_ = s;
        return s;
      }
    }
    /**
     * <code>optional string stan = 8;</code>
     * @return The bytes for stan.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStanBytes() {
      java.lang.Object ref = stan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULTCODE_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object resultCode_ = "";
    /**
     * <code>optional string resultCode = 9;</code>
     * @return Whether the resultCode field is set.
     */
    @java.lang.Override
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string resultCode = 9;</code>
     * @return The resultCode.
     */
    @java.lang.Override
    public java.lang.String getResultCode() {
      java.lang.Object ref = resultCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string resultCode = 9;</code>
     * @return The bytes for resultCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultCodeBytes() {
      java.lang.Object ref = resultCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != Transactions.TransactionStatus.Pending.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (type_ != Transactions.TransactionType.Sale.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (amount_ != 0) {
        output.writeInt32(3, amount_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, referenceNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, arqc_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, maskPan_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, authorizationNumber_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, stan_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, resultCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != Transactions.TransactionStatus.Pending.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (type_ != Transactions.TransactionType.Sale.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, amount_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, referenceNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, arqc_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, maskPan_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, authorizationNumber_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, stan_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, resultCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transactions.Transaction)) {
        return super.equals(obj);
      }
      Transactions.Transaction other = (Transactions.Transaction) obj;

      if (status_ != other.status_) return false;
      if (type_ != other.type_) return false;
      if (getAmount()
          != other.getAmount()) return false;
      if (hasReferenceNumber() != other.hasReferenceNumber()) return false;
      if (hasReferenceNumber()) {
        if (!getReferenceNumber()
            .equals(other.getReferenceNumber())) return false;
      }
      if (hasArqc() != other.hasArqc()) return false;
      if (hasArqc()) {
        if (!getArqc()
            .equals(other.getArqc())) return false;
      }
      if (hasMaskPan() != other.hasMaskPan()) return false;
      if (hasMaskPan()) {
        if (!getMaskPan()
            .equals(other.getMaskPan())) return false;
      }
      if (hasAuthorizationNumber() != other.hasAuthorizationNumber()) return false;
      if (hasAuthorizationNumber()) {
        if (!getAuthorizationNumber()
            .equals(other.getAuthorizationNumber())) return false;
      }
      if (hasStan() != other.hasStan()) return false;
      if (hasStan()) {
        if (!getStan()
            .equals(other.getStan())) return false;
      }
      if (hasResultCode() != other.hasResultCode()) return false;
      if (hasResultCode()) {
        if (!getResultCode()
            .equals(other.getResultCode())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      if (hasReferenceNumber()) {
        hash = (37 * hash) + REFERENCENUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getReferenceNumber().hashCode();
      }
      if (hasArqc()) {
        hash = (37 * hash) + ARQC_FIELD_NUMBER;
        hash = (53 * hash) + getArqc().hashCode();
      }
      if (hasMaskPan()) {
        hash = (37 * hash) + MASKPAN_FIELD_NUMBER;
        hash = (53 * hash) + getMaskPan().hashCode();
      }
      if (hasAuthorizationNumber()) {
        hash = (37 * hash) + AUTHORIZATIONNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getAuthorizationNumber().hashCode();
      }
      if (hasStan()) {
        hash = (37 * hash) + STAN_FIELD_NUMBER;
        hash = (53 * hash) + getStan().hashCode();
      }
      if (hasResultCode()) {
        hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
        hash = (53 * hash) + getResultCode().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transactions.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transactions.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transactions.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transactions.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transactions.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transactions.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transactions.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Transactions.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Transactions.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Transactions.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transactions.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Transactions.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transactions.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transaction)
        Transactions.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Transactions.internal_static_Transaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Transactions.internal_static_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transactions.Transaction.class, Transactions.Transaction.Builder.class);
      }

      // Construct using Transactions.Transaction.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        type_ = 0;
        amount_ = 0;
        referenceNumber_ = "";
        arqc_ = "";
        maskPan_ = "";
        authorizationNumber_ = "";
        stan_ = "";
        resultCode_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Transactions.internal_static_Transaction_descriptor;
      }

      @java.lang.Override
      public Transactions.Transaction getDefaultInstanceForType() {
        return Transactions.Transaction.getDefaultInstance();
      }

      @java.lang.Override
      public Transactions.Transaction build() {
        Transactions.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Transactions.Transaction buildPartial() {
        Transactions.Transaction result = new Transactions.Transaction(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Transactions.Transaction result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.amount_ = amount_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.referenceNumber_ = referenceNumber_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.arqc_ = arqc_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.maskPan_ = maskPan_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.authorizationNumber_ = authorizationNumber_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.stan_ = stan_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.resultCode_ = resultCode_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transactions.Transaction) {
          return mergeFrom((Transactions.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transactions.Transaction other) {
        if (other == Transactions.Transaction.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (other.hasReferenceNumber()) {
          referenceNumber_ = other.referenceNumber_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasArqc()) {
          arqc_ = other.arqc_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasMaskPan()) {
          maskPan_ = other.maskPan_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasAuthorizationNumber()) {
          authorizationNumber_ = other.authorizationNumber_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.hasStan()) {
          stan_ = other.stan_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.hasResultCode()) {
          resultCode_ = other.resultCode_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                amount_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                referenceNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                arqc_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                maskPan_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                authorizationNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                stan_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                resultCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>.TransactionStatus status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.TransactionStatus status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.TransactionStatus status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public Transactions.TransactionStatus getStatus() {
        Transactions.TransactionStatus result = Transactions.TransactionStatus.forNumber(status_);
        return result == null ? Transactions.TransactionStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.TransactionStatus status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(Transactions.TransactionStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.TransactionStatus status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.TransactionType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.TransactionType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.TransactionType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public Transactions.TransactionType getType() {
        Transactions.TransactionType result = Transactions.TransactionType.forNumber(type_);
        return result == null ? Transactions.TransactionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.TransactionType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(Transactions.TransactionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.TransactionType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>int32 amount = 3;</code>
       * @return The amount.
       */
      @java.lang.Override
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>int32 amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(int value) {

        amount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object referenceNumber_ = "";
      /**
       * <code>optional string referenceNumber = 4;</code>
       * @return Whether the referenceNumber field is set.
       */
      public boolean hasReferenceNumber() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string referenceNumber = 4;</code>
       * @return The referenceNumber.
       */
      public java.lang.String getReferenceNumber() {
        java.lang.Object ref = referenceNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          referenceNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string referenceNumber = 4;</code>
       * @return The bytes for referenceNumber.
       */
      public com.google.protobuf.ByteString
          getReferenceNumberBytes() {
        java.lang.Object ref = referenceNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referenceNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string referenceNumber = 4;</code>
       * @param value The referenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setReferenceNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        referenceNumber_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string referenceNumber = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReferenceNumber() {
        referenceNumber_ = getDefaultInstance().getReferenceNumber();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string referenceNumber = 4;</code>
       * @param value The bytes for referenceNumber to set.
       * @return This builder for chaining.
       */
      public Builder setReferenceNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        referenceNumber_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object arqc_ = "";
      /**
       * <code>optional string arqc = 5;</code>
       * @return Whether the arqc field is set.
       */
      public boolean hasArqc() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string arqc = 5;</code>
       * @return The arqc.
       */
      public java.lang.String getArqc() {
        java.lang.Object ref = arqc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          arqc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string arqc = 5;</code>
       * @return The bytes for arqc.
       */
      public com.google.protobuf.ByteString
          getArqcBytes() {
        java.lang.Object ref = arqc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          arqc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string arqc = 5;</code>
       * @param value The arqc to set.
       * @return This builder for chaining.
       */
      public Builder setArqc(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        arqc_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string arqc = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearArqc() {
        arqc_ = getDefaultInstance().getArqc();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string arqc = 5;</code>
       * @param value The bytes for arqc to set.
       * @return This builder for chaining.
       */
      public Builder setArqcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        arqc_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object maskPan_ = "";
      /**
       * <code>optional string maskPan = 6;</code>
       * @return Whether the maskPan field is set.
       */
      public boolean hasMaskPan() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string maskPan = 6;</code>
       * @return The maskPan.
       */
      public java.lang.String getMaskPan() {
        java.lang.Object ref = maskPan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          maskPan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string maskPan = 6;</code>
       * @return The bytes for maskPan.
       */
      public com.google.protobuf.ByteString
          getMaskPanBytes() {
        java.lang.Object ref = maskPan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          maskPan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string maskPan = 6;</code>
       * @param value The maskPan to set.
       * @return This builder for chaining.
       */
      public Builder setMaskPan(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        maskPan_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string maskPan = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaskPan() {
        maskPan_ = getDefaultInstance().getMaskPan();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string maskPan = 6;</code>
       * @param value The bytes for maskPan to set.
       * @return This builder for chaining.
       */
      public Builder setMaskPanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        maskPan_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object authorizationNumber_ = "";
      /**
       * <code>optional string authorizationNumber = 7;</code>
       * @return Whether the authorizationNumber field is set.
       */
      public boolean hasAuthorizationNumber() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string authorizationNumber = 7;</code>
       * @return The authorizationNumber.
       */
      public java.lang.String getAuthorizationNumber() {
        java.lang.Object ref = authorizationNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authorizationNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string authorizationNumber = 7;</code>
       * @return The bytes for authorizationNumber.
       */
      public com.google.protobuf.ByteString
          getAuthorizationNumberBytes() {
        java.lang.Object ref = authorizationNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authorizationNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string authorizationNumber = 7;</code>
       * @param value The authorizationNumber to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        authorizationNumber_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional string authorizationNumber = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorizationNumber() {
        authorizationNumber_ = getDefaultInstance().getAuthorizationNumber();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>optional string authorizationNumber = 7;</code>
       * @param value The bytes for authorizationNumber to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        authorizationNumber_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object stan_ = "";
      /**
       * <code>optional string stan = 8;</code>
       * @return Whether the stan field is set.
       */
      public boolean hasStan() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string stan = 8;</code>
       * @return The stan.
       */
      public java.lang.String getStan() {
        java.lang.Object ref = stan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stan = 8;</code>
       * @return The bytes for stan.
       */
      public com.google.protobuf.ByteString
          getStanBytes() {
        java.lang.Object ref = stan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stan = 8;</code>
       * @param value The stan to set.
       * @return This builder for chaining.
       */
      public Builder setStan(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stan_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stan = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStan() {
        stan_ = getDefaultInstance().getStan();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>optional string stan = 8;</code>
       * @param value The bytes for stan to set.
       * @return This builder for chaining.
       */
      public Builder setStanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stan_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object resultCode_ = "";
      /**
       * <code>optional string resultCode = 9;</code>
       * @return Whether the resultCode field is set.
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string resultCode = 9;</code>
       * @return The resultCode.
       */
      public java.lang.String getResultCode() {
        java.lang.Object ref = resultCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resultCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultCode = 9;</code>
       * @return The bytes for resultCode.
       */
      public com.google.protobuf.ByteString
          getResultCodeBytes() {
        java.lang.Object ref = resultCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultCode = 9;</code>
       * @param value The resultCode to set.
       * @return This builder for chaining.
       */
      public Builder setResultCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        resultCode_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultCode = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultCode() {
        resultCode_ = getDefaultInstance().getResultCode();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultCode = 9;</code>
       * @param value The bytes for resultCode to set.
       * @return This builder for chaining.
       */
      public Builder setResultCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        resultCode_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Transaction)
    }

    // @@protoc_insertion_point(class_scope:Transaction)
    private static final Transactions.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transactions.Transaction();
    }

    public static Transactions.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      @java.lang.Override
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Transactions.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022transactions.proto\"\317\002\n\013Transaction\022\"\n\006" +
      "status\030\001 \001(\0162\022.TransactionStatus\022\036\n\004type" +
      "\030\002 \001(\0162\020.TransactionType\022\016\n\006amount\030\003 \001(\005" +
      "\022\034\n\017referenceNumber\030\004 \001(\tH\000\210\001\001\022\021\n\004arqc\030\005" +
      " \001(\tH\001\210\001\001\022\024\n\007maskPan\030\006 \001(\tH\002\210\001\001\022 \n\023autho" +
      "rizationNumber\030\007 \001(\tH\003\210\001\001\022\021\n\004stan\030\010 \001(\tH" +
      "\004\210\001\001\022\027\n\nresultCode\030\t \001(\tH\005\210\001\001B\022\n\020_refere" +
      "nceNumberB\007\n\005_arqcB\n\n\010_maskPanB\026\n\024_autho" +
      "rizationNumberB\007\n\005_stanB\r\n\013_resultCode*\033" +
      "\n\017TransactionType\022\010\n\004Sale\020\000*U\n\021Transacti" +
      "onStatus\022\013\n\007Pending\020\000\022\n\n\006Failed\020\001\022\r\n\tCan" +
      "celled\020\002\022\n\n\006Denied\020\003\022\014\n\010Approved\020\004b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "Status", "Type", "Amount", "ReferenceNumber", "Arqc", "MaskPan", "AuthorizationNumber", "Stan", "ResultCode", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
