// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: test_conect.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")

package com.example.client_content.transaction_service.data.proto
